# Generated by Django 4.2.6 on 2024-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='Username',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
