# Generated by Django 4.2.6 on 2024-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
