# Generated by Django 4.2.6 on 2024-01-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_city_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city_tb')),
            ],
        ),
    ]
